{
  "result":
  [
    {
        "name": "Chevrolet Impala",
        "description": Cкорость 200 км/ч., мощность 385 л.с., разгон до 100 км/ч. 7.5 сек.",
        "icon": "https://sun9-38.userapi.com/impg/jy8F0LpswlgxQLL8xQM_iYh6qGa4MdB02dsL8A/WEfYKX5ZkwE.jpg?size=414x300&quality=96&proxy=1&sign=a473709855f09051cc3a0280331a3302&type=album",
        "price": "12499$",
        "number": "+79998751997"
    }
  ] 
}
